/*
  회원 이름 표시 규칙(2026-10-03) — 관리자 화면에는 가입 때 사용자가 입력/확인한 실제 이름만 보여준다.
  소셜 가입(특히 Apple: 이름 미제공)에서 이름이 없으면 이메일 앞부분/랜덤 handle이 이름으로 저장돼 "92wr87mcz5" 같은 값이 관리자에게 보였다.
  실명을 만들어내지 않는다 — 합성 handle로 보이는 값은 "이름 미등록"으로 표시하고(전화번호와 함께 구분 가능), 실제 이름은 사용자가 가입 마무리에서 입력한다.
*/
export const UNNAMED_MEMBER_LABEL = "이름 미등록";

// 합성 handle 판별: 소문자 영문+숫자만이고 숫자를 포함하며 8~24자(이메일 local part/랜덤 id 형태). 한글/공백/대문자가 있으면 실제 이름으로 본다.
export function isSyntheticMemberName(name: string | null | undefined): boolean {
  const n = (name ?? "").trim();
  if (!n) return true;
  if (n === "회원" || n === "(이름 없음)") return true;
  return /^(?=.*\d)[a-z0-9]{8,24}$/.test(n);
}

export function displayMemberName(name: string | null | undefined): string {
  return isSyntheticMemberName(name) ? UNNAMED_MEMBER_LABEL : (name as string).trim();
}

/*
  소셜 가입 마무리(SessionWatcher) gate 판정. 소셜 계정만 대상이며 이메일 계정에는 gate가 생기지 않는다.
  - "full": 전화번호가 없음 → 기존 전화 인증 흐름(이름 포함)
  - "name": 전화번호는 있지만 대표 이름(accounts.name 또는 primary profile 이름)이 합성/미등록 → 이름만 받는다(저장된 전화번호는 건드리지 않는다)
  - null: 필요 없음
*/
// 앱이 자동으로 만든 이름 판별(2026-10-03 보완): ensureAccountForCurrentUser는 소셜 provider가 이름을 주지 않으면 user.email의 local-part(@ 앞)를 이름으로 저장한다
// ("johnsmith", "john.smith", "abc_def"). 저장 당시의 출처를 따로 기록한 필드는 없으므로(auth metadata에도 이름 출처 없음, DB 스키마 변경 금지) 현재 로그인 이메일의
// local-part와 "정확히 같은" 이름을 자동 생성으로 본다 — "영문이면 전부 합성" 같은 넓은 heuristic은 쓰지 않아 실제 영문 이름을 막지 않는다.
export function isAutoGeneratedName(name: string | null | undefined, emailLocalPart?: string | null): boolean {
  if (isSyntheticMemberName(name)) return true;
  const local = (emailLocalPart ?? "").trim().toLowerCase();
  return local !== "" && (name ?? "").trim().toLowerCase() === local;
}

export type SocialCompletionNeed = "full" | "name" | null;
export function socialCompletionNeed(a: { isSocial: boolean; phone: string | null; name: string | null; profileName?: string | null; emailLocalPart?: string | null } | null | undefined): SocialCompletionNeed {
  if (!a || !a.isSocial) return null;
  if (!a.phone) return "full";
  if (isAutoGeneratedName(a.name, a.emailLocalPart) || isAutoGeneratedName(a.profileName === undefined ? a.name : a.profileName, a.emailLocalPart)) return "name";
  return null;
}

/*
  기존 소셜 계정의 이름 자동 복구 계획(순수 함수, 2026-10-03) — 우선순위: 모하빗에 저장된 정상 이름 > 신뢰 가능한 provider 이름(autoSave) > 사용자 직접 입력 gate > placeholder.
  · 소셜 계정만 대상. accounts.name과 대표 프로필 이름이 "둘 다 정상"이면 건드리지 않는다(서로 다르면 임의로 고르지 않고 그대로 둔다).
  · 한쪽만 정상이면 그 정상 저장값으로 다른 쪽을 맞춘다(provider 이름으로 덮어쓰지 않는다).
  · 둘 다 자동 생성/미등록일 때만 provider 이름으로 복구하되, 후보가 autoSave(Google/Apple/Naver)일 때만. 카카오 nickname처럼 autoSave가 아닌 후보는 저장하지 않고 입력칸 prefill(suggestedName)로만 돌려준다.
  · profileName === undefined(프로필 없음/조회 실패)이면 어떤 DB 변경도 계획하지 않는다.
*/
export type NameRecoveryPlan =
  | { action: "none"; suggestedName: string | null; conflict?: boolean }
  | { action: "sync_profile_from_account"; name: string; suggestedName: null }
  | { action: "sync_account_from_profile"; name: string; suggestedName: null }
  | { action: "save_candidate"; name: string; suggestedName: null };

export function planNameRecovery(a: {
  isSocial: boolean; accountName: string | null; profileName: string | null | undefined; emailLocalPart?: string | null;
  candidate: { name: string; autoSave: boolean } | null;
}): NameRecoveryPlan {
  const cand = a.candidate && !isAutoGeneratedName(a.candidate.name, a.emailLocalPart) ? a.candidate : null;   // 후보 자체가 자동 생성 이름이면 쓰지 않는다
  if (!a.isSocial) return { action: "none", suggestedName: null };
  const accAuto = isAutoGeneratedName(a.accountName, a.emailLocalPart);
  if (a.profileName === undefined) return { action: "none", suggestedName: accAuto ? cand?.name ?? null : null };
  const profAuto = isAutoGeneratedName(a.profileName, a.emailLocalPart);
  if (!accAuto && !profAuto) {
    const same = (a.accountName ?? "").trim() === (a.profileName ?? "").trim();
    return same ? { action: "none", suggestedName: null } : { action: "none", suggestedName: null, conflict: true };   // 서로 다른 정상 이름: 임의 선택 금지
  }
  if (!accAuto && profAuto) return { action: "sync_profile_from_account", name: (a.accountName as string).trim(), suggestedName: null };
  if (accAuto && !profAuto) return { action: "sync_account_from_profile", name: (a.profileName as string).trim(), suggestedName: null };
  if (cand?.autoSave) return { action: "save_candidate", name: cand.name, suggestedName: null };
  return { action: "none", suggestedName: cand?.name ?? null };
}
