/* 후속 보완(2026-10-03): ① 수업 목록 stale race(성공/실패 모두) ② 이메일 local-part로 자동 생성된 소셜 이름 판정 */
import { readFileSync } from "node:fs";
import { join } from "node:path";
import { describe, expect, it } from "vitest";
import { loadClassOptionsGuarded } from "../../lib/classOptionsLoader";
import { isAutoGeneratedName, socialCompletionNeed } from "../../lib/memberName";

const read = (p: string) => readFileSync(join(__dirname, "../..", p), "utf-8");

// 수동으로 resolve/reject를 제어하는 요청 + 센터 선택/표시 목록을 가진 작은 하니스
function harness() {
  let current: string | null = null;
  let shown: string[] = ["(초기 stale)"];
  const pending = new Map<string, { resolve: (v: string[]) => void; reject: (e: Error) => void }>();
  const fetchOptions = (cid: string) => new Promise<string[]>((resolve, reject) => pending.set(cid, { resolve, reject }));
  const load = (centerId: string | null) => loadClassOptionsGuarded({ centerId, getCurrent: () => current, fetchOptions, setOptions: (l) => { shown = l; } });
  return {
    select: (cid: string | null) => { current = cid; },   // centerId 변경을 추적하는 effect가 하는 일(loader는 덮어쓰지 않는다)
    load, pending, shown: () => shown,
  };
}
const tick = () => new Promise((r) => setTimeout(r, 0));

describe("수업 목록 stale race", () => {
  it("A: A 요청 시작 → B로 변경 → B 성공 → A 늦게 실패 → B 목록 유지", async () => {
    const h = harness();
    h.select("A"); const a = h.load("A");
    h.select("B"); const b = h.load("B");
    h.pending.get("B")!.resolve(["B수업"]); await b;
    expect(h.shown()).toEqual(["B수업"]);
    h.pending.get("A")!.reject(new Error("timeout")); await a;
    expect(h.shown()).toEqual(["B수업"]);   // 오래된 실패가 현재(B) 목록을 지우지 않는다
  });
  it("B: A 요청 시작 → B로 변경 → A 늦게 성공 → B(진행 중/완료) 목록을 A 데이터로 덮지 않음", async () => {
    const h = harness();
    h.select("A"); const a = h.load("A");
    h.select("B"); const b = h.load("B");
    h.pending.get("A")!.resolve(["A수업"]); await a;
    expect(h.shown()).toEqual([]);          // B 로딩 중: A 데이터가 보이면 안 된다
    h.pending.get("B")!.resolve(["B수업"]); await b;
    expect(h.shown()).toEqual(["B수업"]);
    // 이미 B가 표시된 뒤 A가 성공해도 동일
    const h2 = harness();
    h2.select("A"); const a2 = h2.load("A"); h2.select("B"); const b2 = h2.load("B");
    h2.pending.get("B")!.resolve(["B수업"]); await b2;
    h2.pending.get("A")!.resolve(["A수업"]); await a2;
    expect(h2.shown()).toEqual(["B수업"]);
  });
  it("C: 현재 센터 요청 자체가 실패 → 기존 stale 목록은 남지 않고 빈 목록", async () => {
    const h = harness();
    h.select("A");
    const p = h.load("A");
    expect(h.shown()).toEqual([]);          // 열자마자 stale 목록 제거(기존 UX 유지)
    h.pending.get("A")!.reject(new Error("network")); await p;
    expect(h.shown()).toEqual([]);
  });
  it("센터 없음이면 요청 없이 빈 목록, 센터 선택 변경 없이 정상 성공은 반영", async () => {
    const h = harness();
    await h.load(null);
    expect(h.shown()).toEqual([]);
    expect(h.pending.size).toBe(0);
    h.select("A"); const p = h.load("A"); h.pending.get("A")!.resolve(["A수업"]); await p; await tick();
    expect(h.shown()).toEqual(["A수업"]);
  });
  it("페이지: centerIdRef는 centerId effect에서만 갱신(loader/loadClassOptions가 덮어쓰지 않음), 단건/일괄이 같은 helper 사용", () => {
    const p = read("app/manager/membership-rules/page.tsx");
    expect(p.match(/centerIdRef\.current\s*=/g)).toHaveLength(1);
    expect(p).toContain("useEffect(() => { centerIdRef.current = centerId; setExistingClasses([]); }, [centerId]);");
    expect(p).toContain("getCurrent: () => centerIdRef.current");
    const bulk = p.slice(p.indexOf("async function openBulkRuleSheet"), p.indexOf("async function handleBulkAddRules"));
    expect(bulk).toContain("await loadClassOptions();");
    const single = p.slice(p.indexOf("async function openRuleSheet"), p.indexOf("async function loadClassOptions"));
    expect(single).toContain("await loadClassOptions();");
    const loader = read("lib/classOptionsLoader.ts");
    expect(loader).toContain("if (getCurrent() === centerId) setOptions(list);");
    expect(loader).toContain("if (getCurrent() === centerId) setOptions([]);");
    expect(loader).not.toMatch(/centerIdRef|\.current\s*=/);
  });
});

describe("자동 생성 이름(이메일 local-part) 판정", () => {
  const S = (o: Partial<{ isSocial: boolean; phone: string | null; name: string | null; profileName: string | null; emailLocalPart: string | null }>) =>
    ({ isSocial: true, phone: "01012345678", name: "홍길동", profileName: "홍길동", emailLocalPart: "hong.gildong", ...o });
  it("johnsmith / john.smith / abc_def가 이메일 local-part에서 자동 생성된 이름이면 name gate", () => {
    for (const [name, local] of [["johnsmith", "johnsmith"], ["john.smith", "john.smith"], ["abc_def", "abc_def"], ["JohnSmith", "johnsmith"]]) {
      expect(socialCompletionNeed(S({ name, profileName: name, emailLocalPart: local }))).toBe("name");
    }
    // 대표 프로필만 자동 이름이어도(accounts는 실명) gate
    expect(socialCompletionNeed(S({ name: "홍길동", profileName: "johnsmith", emailLocalPart: "johnsmith" }))).toBe("name");
  });
  it("실제 영문/한글 이름은 막지 않는다 — 이메일과 다르면 gate 없음(넓은 heuristic 미사용)", () => {
    for (const [name, local] of [["John Smith", "jsmith77"], ["Minsu Kim", "minsu_kim"], ["john", "jsmith"], ["홍길동", "hong"], ["김민수", null], ["David", "david.lee"]] as const) {
      expect(socialCompletionNeed(S({ name, profileName: name, emailLocalPart: local }))).toBeNull();
    }
    expect(isAutoGeneratedName("John Smith", "john.smith")).toBe(false);   // 공백 포함 이름 ≠ local-part
  });
  it("기존 합성 handle(숫자 포함 8~24자)과 빈/기본값은 이메일 정보 없이도 자동 이름", () => {
    expect(isAutoGeneratedName("92wr87mcz5", null)).toBe(true);
    expect(isAutoGeneratedName("", "x")).toBe(true);
    expect(isAutoGeneratedName("회원", undefined)).toBe(true);
    expect(isAutoGeneratedName("홍길동", undefined)).toBe(false);
  });
  it("email 회원은 새 gate 없음, phone 없는 소셜은 full, phone 있는 소셜 정상 이름은 gate 없음", () => {
    expect(socialCompletionNeed(S({ isSocial: false, name: "johnsmith", profileName: "johnsmith", emailLocalPart: "johnsmith" }))).toBeNull();
    expect(socialCompletionNeed(S({ phone: null }))).toBe("full");
    expect(socialCompletionNeed(S({}))).toBeNull();
  });
  it("자동 이름을 name-only 화면에서 다시 입력해도 거부, 이름 입력 prefill은 자동 이름이면 비움, phone/address 값은 저장 경로에 없다", () => {
    const w = read("app/components/SessionWatcher.tsx");
    expect(w).toContain("isAutoGeneratedName(realName, authLocalPart)");
    expect(w).toContain('setRealName(isAutoGeneratedName(account.name, account.emailLocalPart) ? "" : (account.name ?? ""))');
    const nameFn = w.slice(w.indexOf("async function handleCompleteName"), w.indexOf("async function handleCancelOnboarding") > 0 ? w.indexOf("async function handleCancelOnboarding") : undefined);
    expect(nameFn).toContain("completeSocialName(nameGateAccountId, realName.trim())");
    expect(nameFn).not.toMatch(/phone|address|agreeMarketing/);
    const a = read("lib/authAccount.ts");
    expect(a).toContain("const emailLocalPart = user.email ? user.email.split(\"@\")[0] : null;");
    expect(a).not.toMatch(/user_metadata[^\n]*name_source/);   // DB/metadata 스키마 변경 없음
  });
});
