/* 소셜 로그인 이름 자동 복구/자동 입력(2026-10-03) — Production 호출 없이 in-memory fake로 ensureAccountForCurrentUser의 동작을 검증한다. */
import { readFileSync } from "node:fs";
import { join } from "node:path";
import { beforeEach, describe, expect, it, vi } from "vitest";

const read = (p: string) => readFileSync(join(__dirname, "../..", p), "utf-8");

// ---- sessionStorage stub (node 환경)
const mem = new Map<string, string>();
vi.stubGlobal("sessionStorage", { getItem: (k: string) => mem.get(k) ?? null, setItem: (k: string, v: string) => void mem.set(k, v), removeItem: (k: string) => void mem.delete(k) });

// ---- in-memory supabase
type Row = Record<string, any>;
const db: { accounts: Row[]; profiles: Row[] } = { accounts: [], profiles: [] };
let currentUser: any = null;
let failUpdate: Record<string, boolean> = {};
const writes: { table: string; patch: Row }[] = [];
let seq = 0;
function from(table: "accounts" | "profiles") {
  let op: "select" | "update" | "insert" = "select"; let patch: Row = {}; let ins: Row = {}; const filters: ((r: Row) => boolean)[] = [];
  const run = (mode: "many" | "maybe" | "single") => {
    const matched = db[table].filter((r) => filters.every((f) => f(r)));
    if (op === "update") {
      if (failUpdate[table]) return Promise.resolve({ data: null, error: { message: "RLS" } });
      writes.push({ table, patch });
      for (const r of matched) Object.assign(r, patch);
      return Promise.resolve({ data: matched.map((r) => ({ id: r.id })), error: null });
    }
    if (op === "insert") { const row = { id: `${table}-${++seq}`, ...ins, deleted_at: null }; db[table].push(row); return Promise.resolve({ data: mode === "many" ? [row] : row, error: null }); }
    const data = mode === "many" ? matched : (matched[0] ?? null);
    return Promise.resolve({ data, error: null });
  };
  const api: any = {
    select() { return api; }, update(p: Row) { op = "update"; patch = p; return api; }, insert(r: Row) { op = "insert"; ins = r; return api; },
    eq(c: string, v: any) { filters.push((r) => r[c] === v); return api; }, is(c: string, v: any) { filters.push((r) => (r[c] ?? null) === v); return api; }, limit() { return api; },
    maybeSingle() { return run("maybe"); }, single() { return run("single"); }, then(res: any, rej: any) { return run("many").then(res, rej); },
  };
  return api;
}
vi.mock("../../lib/supabaseClient", () => ({
  supabase: {
    from: (t: any) => from(t),
    auth: { getUser: async () => ({ data: { user: currentUser } }) },
    rpc: async (name: string) => (name === "my_account_id" ? { data: db.accounts.find((a) => a.auth_id === currentUser?.id)?.id ?? null, error: null } : { data: null, error: null }),
  },
}));
import { ensureAccountForCurrentUser } from "../../lib/authAccount";
import { clearSocialNameStash, consumeSocialNameCandidate, metadataNameCandidate, normalizeCandidateName, SOCIAL_NAME_STASH_KEY, SOCIAL_NAME_STASH_TTL_MS, stashSocialName, socialProviderOf } from "../../lib/socialName";
import { displayMemberName, isAutoGeneratedName, planNameRecovery, socialCompletionNeed } from "../../lib/memberName";

const SYN = "92wr87mcz5";   // 합성 handle
const userOf = (provider: "google" | "apple" | "naver" | "kakao", extra: Row = {}, email = "someone@example.com") => ({
  id: "auth-1", email,
  app_metadata: { provider: provider === "google" || provider === "apple" ? provider : "email" },
  user_metadata: { ...(provider === "naver" || provider === "kakao" ? { provider } : {}), ...extra },
});
const seed = (accName: string | null, profName: string | null | undefined, phone: string | null = "01012345678") => {
  db.accounts = [{ id: "acc-1", auth_id: "auth-1", name: accName, phone }];
  db.profiles = profName === undefined ? [] : [{ id: "prof-1", account_id: "acc-1", name: profName, is_primary: true, deleted_at: null }];
};
const names = () => ({ acc: db.accounts[0]?.name, prof: db.profiles[0]?.name });
const login = async (user: any) => { currentUser = user; return ensureAccountForCurrentUser(); };

beforeEach(() => { mem.clear(); db.accounts = []; db.profiles = []; failUpdate = {}; writes.length = 0; seq = 0; currentUser = null; });

describe("socialName stash/후보 helper", () => {
  it("placeholder/빈값/너무 긴 값/이메일은 후보가 아니다(저장 금지)", () => {
    for (const bad of ["", "   ", "회원", "카카오 회원", "네이버 회원", "카카오회원", "Naver Member", null, undefined, 123, "a".repeat(31), "a@b.com"]) expect(normalizeCandidateName(bad as any)).toBeNull();
    expect(normalizeCandidateName("  홍   길동 ")).toBe("홍 길동");
    for (const [prov, v] of [["kakao", "카카오 회원"], ["naver", "네이버 회원"], ["google", "회원"]] as const) {
      expect(stashSocialName(prov, v)).toBe(false);
      expect(mem.has(SOCIAL_NAME_STASH_KEY)).toBe(false);
    }
  });
  it("stash는 provider별로 격리 — 다른 provider 로그인에는 쓰이지 않고(그리고 제거되고), 만료되면 버린다", () => {
    stashSocialName("google", "홍길동");
    expect(consumeSocialNameCandidate("naver")).toBeNull();
    expect(mem.has(SOCIAL_NAME_STASH_KEY)).toBe(false);           // 어떤 경우든 consume하면 제거
    stashSocialName("google", "홍길동", { now: 1000 });
    expect(consumeSocialNameCandidate("google", { now: 1000 + SOCIAL_NAME_STASH_TTL_MS + 1 })).toBeNull();   // 만료
    stashSocialName("google", "홍길동");
    expect(consumeSocialNameCandidate("google")).toEqual({ provider: "google", name: "홍길동", autoSave: true });
    expect(consumeSocialNameCandidate("google")).toBeNull();      // 한 번만
  });
  it("autoSave는 provider 정책을 넘을 수 없다(카카오는 항상 false), 새 stash는 이전 stash를 덮어쓰고 이름이 없으면 지운다", () => {
    stashSocialName("kakao", "닉네임", { autoSave: true });
    expect(consumeSocialNameCandidate("kakao")).toEqual({ provider: "kakao", name: "닉네임", autoSave: false });
    stashSocialName("google", "A"); stashSocialName("naver", "B");
    expect(consumeSocialNameCandidate("google")).toBeNull();
    stashSocialName("naver", "B"); stashSocialName("naver", null);   // 이름 없음 → 이전 stash 제거
    expect(consumeSocialNameCandidate("naver")).toBeNull();
    stashSocialName("apple", "C"); clearSocialNameStash();            // 로그인 실패/취소
    expect(consumeSocialNameCandidate("apple")).toBeNull();
  });
  it("provider 판별 + metadata 후보(구글 웹 full_name/name 신뢰, 카카오는 prefill 전용, 이메일 로그인은 없음)", () => {
    expect(socialProviderOf(userOf("kakao"))).toBe("kakao"); expect(socialProviderOf(userOf("google"))).toBe("google");
    expect(socialProviderOf({ app_metadata: { provider: "email" }, user_metadata: {} })).toBeNull();
    expect(metadataNameCandidate(userOf("google", { full_name: "홍길동" }))).toEqual({ provider: "google", name: "홍길동", autoSave: true });
    expect(metadataNameCandidate(userOf("kakao", { name: "닉" }))).toEqual({ provider: "kakao", name: "닉", autoSave: false });
    expect(metadataNameCandidate(userOf("naver", { name: "네이버 회원" }))).toBeNull();
    expect(metadataNameCandidate({ app_metadata: { provider: "email" }, user_metadata: { full_name: "x" } })).toBeNull();
  });
});

describe("planNameRecovery 우선순위(모하빗 정상 이름 > provider 이름 > 사용자 입력 > placeholder)", () => {
  const cand = { name: "홍길동", autoSave: true };
  const base = { isSocial: true, emailLocalPart: "someone" };
  it("둘 다 합성 + autoSave 후보 → 후보 저장 / autoSave 아님 → 저장 없이 suggestedName", () => {
    expect(planNameRecovery({ ...base, accountName: SYN, profileName: SYN, candidate: cand })).toEqual({ action: "save_candidate", name: "홍길동", suggestedName: null });
    expect(planNameRecovery({ ...base, accountName: SYN, profileName: SYN, candidate: { name: "닉", autoSave: false } })).toEqual({ action: "none", suggestedName: "닉" });
    expect(planNameRecovery({ ...base, accountName: SYN, profileName: SYN, candidate: null })).toEqual({ action: "none", suggestedName: null });
  });
  it("정상 저장 이름이 하나라도 있으면 그것이 기준(provider 후보로 덮어쓰지 않음), 둘 다 정상이면 불변(서로 다르면 conflict만 표시)", () => {
    expect(planNameRecovery({ ...base, accountName: "김모하", profileName: SYN, candidate: cand })).toEqual({ action: "sync_profile_from_account", name: "김모하", suggestedName: null });
    expect(planNameRecovery({ ...base, accountName: SYN, profileName: "김모하", candidate: cand })).toEqual({ action: "sync_account_from_profile", name: "김모하", suggestedName: null });
    expect(planNameRecovery({ ...base, accountName: "김모하", profileName: "김모하", candidate: cand })).toEqual({ action: "none", suggestedName: null });
    expect(planNameRecovery({ ...base, accountName: "김모하", profileName: "이모하", candidate: cand })).toEqual({ action: "none", suggestedName: null, conflict: true });
  });
  it("소셜이 아니거나 프로필이 없으면 DB 변경 계획 없음, 후보 자체가 이메일 앞부분(자동 이름)이면 쓰지 않는다", () => {
    expect(planNameRecovery({ isSocial: false, accountName: SYN, profileName: SYN, candidate: cand, emailLocalPart: "x" }).action).toBe("none");
    expect(planNameRecovery({ ...base, accountName: SYN, profileName: undefined, candidate: cand }).action).toBe("none");
    expect(planNameRecovery({ ...base, accountName: SYN, profileName: SYN, candidate: { name: "someone", autoSave: true } })).toEqual({ action: "none", suggestedName: null });
  });
});

describe("ensureAccountForCurrentUser — 기존 계정 자동 복구", () => {
  it("1. Google fullName(native stash) + 기존 accounts/profile 둘 다 합성명 → 둘 다 정상 이름으로 복구, 이름 gate 사라짐", async () => {
    seed(SYN, SYN); stashSocialName("google", "홍길동");
    const r = (await login(userOf("google")))!;
    expect(names()).toEqual({ acc: "홍길동", prof: "홍길동" });
    expect(r.nameRecovered).toBe(true); expect(r.name).toBe("홍길동"); expect(r.profileName).toBe("홍길동");
    expect(socialCompletionNeed(r)).toBeNull();                                        // phone 있음 + 정상 이름 → gate 없음
    expect(writes.map((w) => w.table)).toEqual(["profiles", "accounts"]);               // 대표 프로필 → accounts 순서
    expect(mem.has(SOCIAL_NAME_STASH_KEY)).toBe(false);
  });
  it("1b. Google 웹 OAuth: stash 없이 user_metadata.full_name만 있어도 합성명이면 복구", async () => {
    seed(SYN, SYN);
    const r = (await login(userOf("google", { full_name: "구글웹이름" })))!;
    expect(names()).toEqual({ acc: "구글웹이름", prof: "구글웹이름" }); expect(r.nameRecovered).toBe(true);
  });
  it("2. Naver providerName(callback stash) + 기존 둘 다 합성명 → 복구", async () => {
    seed(SYN, SYN); stashSocialName("naver", "네이버이름");
    const r = (await login(userOf("naver")))!;
    expect(names()).toEqual({ acc: "네이버이름", prof: "네이버이름" }); expect(r.nameRecovered).toBe(true);
  });
  it("3. 기존 정상 모하빗 이름 + provider 이름 → 정상 이름 유지(덮어쓰기 없음, DB write 0)", async () => {
    for (const prov of ["google", "naver", "apple"] as const) {
      seed("김모하", "김모하"); writes.length = 0; stashSocialName(prov, "다른이름");
      const r = (await login(userOf(prov, { full_name: "또다른이름" })))!;
      expect(names()).toEqual({ acc: "김모하", prof: "김모하" }); expect(writes).toHaveLength(0);
      expect(r.nameRecovered).toBe(false); expect(r.suggestedName).toBeNull();
    }
  });
  it("3b. 서로 다른 두 정상 이름은 임의로 하나를 고르지 않고 그대로 둔다", async () => {
    seed("김모하", "이모하"); stashSocialName("google", "구글이름");
    await login(userOf("google"));
    expect(names()).toEqual({ acc: "김모하", prof: "이모하" }); expect(writes).toHaveLength(0);
  });
  it("4. accounts 정상 / profile 합성 → 정상 저장 이름으로 profile 동기화(provider 이름 미사용)", async () => {
    seed("김모하", SYN); stashSocialName("google", "구글이름");
    const r = (await login(userOf("google")))!;
    expect(names()).toEqual({ acc: "김모하", prof: "김모하" }); expect(r.profileName).toBe("김모하");
    expect(writes).toEqual([{ table: "profiles", patch: { name: "김모하" } }]);
  });
  it("5. profile 정상 / accounts 합성 → 정상 profile 이름으로 accounts 동기화", async () => {
    seed(SYN, "김모하"); stashSocialName("naver", "네이버이름");
    const r = (await login(userOf("naver")))!;
    expect(names()).toEqual({ acc: "김모하", prof: "김모하" }); expect(r.name).toBe("김모하");
    expect(writes).toEqual([{ table: "accounts", patch: { name: "김모하" } }]);
  });
  it("6. Apple 최초 fullName → 기존 합성명 복구, 신규 계정은 처음부터 그 이름", async () => {
    seed(SYN, SYN); stashSocialName("apple", "애플이름");
    await login(userOf("apple", {}, "relay@privaterelay.appleid.com"));
    expect(names()).toEqual({ acc: "애플이름", prof: "애플이름" });
    db.accounts = []; db.profiles = []; stashSocialName("apple", "신규애플");
    const r = (await login(userOf("apple", {}, "relay2@privaterelay.appleid.com")))!;
    expect(r.wasCreated).toBe(true); expect(names()).toEqual({ acc: "신규애플", prof: "신규애플" }); expect(socialCompletionNeed({ ...r, phone: null })).toBe("full");
  });
  it("7. Apple 이후 로그인(fullName 없음) → 이름을 만들어내지 않고 gate 유지", async () => {
    seed(SYN, SYN);
    const r = (await login(userOf("apple", {}, "relay@privaterelay.appleid.com")))!;
    expect(names()).toEqual({ acc: SYN, prof: SYN }); expect(writes).toHaveLength(0);
    expect(r.suggestedName).toBeNull(); expect(socialCompletionNeed(r)).toBe("name");
  });
  it("8. Kakao nickname(stash) → DB에 확정 저장하지 않고 이름 입력칸 prefill(suggestedName)만, 사용자가 확인해야 저장(gate 유지)", async () => {
    seed(SYN, SYN); stashSocialName("kakao", "카카오닉네임");
    const r = (await login(userOf("kakao", {}, "kakao-123@example.test")))!;
    expect(names()).toEqual({ acc: SYN, prof: SYN }); expect(writes).toHaveLength(0);
    expect(r.suggestedName).toBe("카카오닉네임"); expect(r.nameRecovered).toBe(false);
    expect(socialCompletionNeed(r)).toBe("name");
  });
  it("8b. 신규 Kakao 가입: nickname을 이름으로 확정하지 않는다(placeholder 저장 → full gate) + prefill 제안", async () => {
    stashSocialName("kakao", "카카오닉네임");
    const r = (await login(userOf("kakao", { name: "카카오닉네임" }, "kakao-123@example.test")))!;
    expect(r.wasCreated).toBe(true); expect(names()).toEqual({ acc: "회원", prof: "회원" });
    expect(r.suggestedName).toBe("카카오닉네임"); expect(socialCompletionNeed(r)).toBe("full");
    expect(displayMemberName(db.accounts[0].name)).toBe("이름 미등록");
  });
  it("8c. 기존 정상 카카오 회원이 이미 저장한 이름은 건드리지 않는다", async () => {
    seed("카카오닉네임", "카카오닉네임"); stashSocialName("kakao", "바뀐닉네임");
    const r = (await login(userOf("kakao", { name: "바뀐닉네임" })))!;
    expect(names()).toEqual({ acc: "카카오닉네임", prof: "카카오닉네임" }); expect(writes).toHaveLength(0); expect(socialCompletionNeed(r)).toBeNull();
  });
  it("9/10. Kakao/Naver placeholder·nickname 없음 → 빈 입력/기존 gate, 자동 저장 없음", async () => {
    seed(SYN, SYN);
    stashSocialName("kakao", "카카오 회원");
    let r = (await login(userOf("kakao", { name: "카카오 회원" })))!;
    expect(r.suggestedName).toBeNull(); expect(names()).toEqual({ acc: SYN, prof: SYN });
    stashSocialName("naver", "네이버 회원");
    r = (await login(userOf("naver", { name: "네이버 회원" })))!;
    expect(r.nameRecovered).toBe(false); expect(names()).toEqual({ acc: SYN, prof: SYN }); expect(socialCompletionNeed(r)).toBe("name");
  });
  it("11/12. stale/오염 stash: 다른 provider·실패 후 남은 stash는 적용되지 않는다", async () => {
    seed(SYN, SYN); stashSocialName("google", "구글이름");
    await login(userOf("naver"));                                                      // 구글 stash가 남은 채 네이버 로그인
    expect(names()).toEqual({ acc: SYN, prof: SYN });
    seed(SYN, SYN); stashSocialName("apple", "애플이름"); clearSocialNameStash();      // 로그인 실패 시 정리
    await login(userOf("apple", {}, "relay@privaterelay.appleid.com"));
    expect(names()).toEqual({ acc: SYN, prof: SYN });
    seed(SYN, SYN); stashSocialName("google", "구글이름", { now: Date.now() - SOCIAL_NAME_STASH_TTL_MS - 5000 });
    await login(userOf("google"));
    expect(names()).toEqual({ acc: SYN, prof: SYN });                                  // 만료된 stash
  });
  it("후보가 이메일 앞부분(자동 생성 이름)이면 복구에 쓰지 않는다", async () => {
    seed(SYN, SYN); stashSocialName("google", "someone");
    await login(userOf("google", {}, "someone@example.com"));
    expect(names()).toEqual({ acc: SYN, prof: SYN });
  });
  it("복구 write가 실패해도 로그인은 계속되고(gate 유지) 이름은 로그/예외에 남지 않는다", async () => {
    seed(SYN, SYN); stashSocialName("google", "홍길동"); failUpdate = { profiles: true };
    const spy = vi.spyOn(console, "error").mockImplementation(() => {});
    const r = (await login(userOf("google")))!;
    expect(names()).toEqual({ acc: SYN, prof: SYN }); expect(socialCompletionNeed(r)).toBe("name");
    expect(JSON.stringify(spy.mock.calls)).not.toContain("홍길동");
    spy.mockRestore();
  });
  it("13. 이메일(비소셜) 회원은 이름 복구/후보 적용 대상이 아니다, stash는 항상 소비된다", async () => {
    seed(SYN, SYN); stashSocialName("google", "홍길동");
    const r = (await login({ id: "auth-1", email: "a@b.com", app_metadata: { provider: "email" }, user_metadata: { full_name: "메타이름" } }))!;
    expect(r.isSocial).toBe(false); expect(names()).toEqual({ acc: SYN, prof: SYN }); expect(writes).toHaveLength(0);
    expect(mem.has(SOCIAL_NAME_STASH_KEY)).toBe(false);
  });
  it("14. 복구된 대표 프로필 이름은 회원 검색 RPC(대표 프로필 p.name)에서 정상 이름으로 보이는 구조", async () => {
    seed(SYN, SYN); stashSocialName("naver", "네이버이름");
    await login(userOf("naver"));
    const primary = db.profiles.find((p) => p.is_primary)!;
    expect(isAutoGeneratedName(primary.name, "x")).toBe(false);
    expect(displayMemberName(primary.name)).toBe("네이버이름");
    expect(read("add_member_candidate_search_20261003.sql")).toContain("p.name as pname");
    expect(read("add_member_candidate_search_20261003.sql")).toContain("p.is_primary = true");
  });
});

describe("조기 실패/취소 경로의 stale stash 제거", () => {
  // handleSocial()이 하는 일 = 새 시도 시작 시 clearSocialNameStash() → provider 인증(취소/실패하면 새 stash 없이 종료)
  const startAttempt = (provider: "google" | "apple", authenticate: () => void) => {
    clearSocialNameStash();
    try { authenticate(); } catch { /* 취소/오류 — 새 stash를 만들기 전에 종료 */ }
  };
  it("1. 이전 Google stash가 남은 상태에서 새 Google 로그인을 시작하면 인증 수행 전에 stash가 지워진다(취소돼도 남지 않음)", () => {
    stashSocialName("google", "이전구글이름");
    let sawStashDuringAuth = true;
    startAttempt("google", () => { sawStashDuringAuth = mem.has(SOCIAL_NAME_STASH_KEY); throw new Error("canceled"); });
    expect(sawStashDuringAuth).toBe(false);
    expect(consumeSocialNameCandidate("google")).toBeNull();
  });
  it("2. 이전 Apple stash가 남은 상태에서 새 Apple 로그인을 시작해도 동일", () => {
    stashSocialName("apple", "이전애플이름");
    let sawStashDuringAuth = true;
    startAttempt("apple", () => { sawStashDuringAuth = mem.has(SOCIAL_NAME_STASH_KEY); throw new Error("native plugin error"); });
    expect(sawStashDuringAuth).toBe(false);
    expect(consumeSocialNameCandidate("apple")).toBeNull();
  });
  it("같은 provider 재시도에서 취소 후 로그인이 stale 후보로 기존 합성 이름을 덮지 않는다(통합)", async () => {
    seed(SYN, SYN); stashSocialName("google", "이전구글이름");
    startAttempt("google", () => { throw new Error("canceled"); });          // 취소
    await login(userOf("google"));                                            // 이후 stash 없이(예: 웹 OAuth) 로그인
    expect(names()).toEqual({ acc: SYN, prof: SYN }); expect(writes).toHaveLength(0);
  });
  it("3/4. Naver·Kakao callback: provider error, code/state 누락·불일치에서도 stash를 지운다(요청 처리 전 early return 경로)", () => {
    for (const file of ["app/login/naver-callback/page.tsx", "app/login/kakao-callback/page.tsx"]) {
      const s = read(file);
      const providerErr = s.slice(s.indexOf("if (providerError) {"), s.indexOf("return;", s.indexOf("if (providerError) {")));
      expect(providerErr).toContain("clearSocialNameStash();");
      expect(providerErr.indexOf("clearSocialNameStash();")).toBeLessThan(providerErr.indexOf("fail("));
      const stateErr = s.slice(s.indexOf("if (!code || !state || !savedState || state !== savedState) {"), s.indexOf("return;", s.indexOf("if (!code || !state || !savedState || state !== savedState) {")));
      expect(stateErr).toContain("clearSocialNameStash();");
      expect(stateErr.indexOf("clearSocialNameStash();")).toBeLessThan(stateErr.indexOf("fail("));
      expect(s.match(/clearSocialNameStash\(\)/g)!.length).toBeGreaterThanOrEqual(4);   // provider error / state / Edge Function error / verifyOtp error
    }
  });
  it("handleSocial: clearSocialNameStash()가 중복 클릭 return 이후, 모든 provider 분기(naver/kakao/apple/google/web OAuth)보다 앞에 있다", () => {
    const s = read("app/login/page.tsx");
    const body = s.slice(s.indexOf("async function handleSocial"));
    const clear = body.indexOf("clearSocialNameStash();");
    expect(clear).toBeGreaterThan(body.indexOf("if (socialLoading) return;"));
    for (const marker of ['if (provider === "naver")', 'startNaverLogin(', 'if (provider === "kakao")', 'startKakaoLogin(', 'if (provider === "apple" && isAppleNativeSignInSupported())', "signInWithAppleNative()", "signInWithGoogleNative()", "signInWithOAuth("]) {
      const idx = body.indexOf(marker);
      expect(idx, marker).toBeGreaterThan(clear);
    }
    expect(s).toContain('import { clearSocialNameStash } from "../../lib/socialName";');
  });
  it("성공 흐름은 그대로: native는 인증 성공 후 새 stash, Kakao autoSave=false 유지", () => {
    expect(read("lib/googleAuth.ts")).toContain('stashSocialName("google", native.fullName, { autoSave: true })');
    expect(read("lib/appleAuth.ts")).toContain('stashSocialName("apple", native.fullName, { autoSave: true })');
    expect(read("app/login/kakao-callback/page.tsx")).toContain('stashSocialName("kakao", data.providerName, { autoSave: false })');
    expect(read("app/login/naver-callback/page.tsx")).toContain('stashSocialName("naver", data.providerName, { autoSave: true })');
  });
});

describe("동시 호출 race", () => {
  it("SIGNED_IN 핸들러와 로그인 화면이 동시에 호출해도 stash는 한 번 소비되고 두 호출 모두 복구된 이름을 본다", async () => {
    seed(SYN, SYN); stashSocialName("google", "홍길동"); currentUser = userOf("google");
    const [a, b] = await Promise.all([ensureAccountForCurrentUser(), ensureAccountForCurrentUser()]);
    expect(names()).toEqual({ acc: "홍길동", prof: "홍길동" });
    expect([a?.name, b?.name]).toEqual(["홍길동", "홍길동"]);
    expect(writes.filter((w) => w.table === "profiles")).toHaveLength(1);   // 중복 복구 write 없음
    const c = await ensureAccountForCurrentUser();                           // 끝난 뒤의 호출은 새로 실행(기존 계정 그대로)
    expect(c?.nameRecovered).toBe(false);
  });
});

describe("정적 계약 — race 방어/provider별 stash/Edge Function/UX", () => {
  it("Apple/Google native: signInWithIdToken 호출 전에 stash, 실패 시 clear, native 파일은 건드리지 않는다", () => {
    for (const [file, call, prov] of [["lib/appleAuth.ts", "await supabase.auth.signInWithIdToken(", "apple"], ["lib/googleAuth.ts", "await supabase.auth.signInWithIdToken(", "google"]] as const) {
      const s = read(file);
      expect(s.indexOf(`stashSocialName("${prov}", native.fullName, { autoSave: true })`)).toBeGreaterThan(0);
      expect(s.indexOf(`stashSocialName("${prov}"`)).toBeLessThan(s.indexOf(call));
      expect(s).toContain("clearSocialNameStash();");
      expect(s).not.toMatch(/console\.(log|error)\([^)]*native\.fullName/);   // 이름 값 로그 금지(hasFullName boolean만)
    }
  });
  it("Naver/Kakao callback: verifyOtp 전에 stash(naver autoSave true / kakao false), 실패 시 clear", () => {
    for (const [file, prov, auto] of [["app/login/naver-callback/page.tsx", "naver", "true"], ["app/login/kakao-callback/page.tsx", "kakao", "false"]] as const) {
      const s = read(file);
      expect(s).toContain(`stashSocialName("${prov}", data.providerName, { autoSave: ${auto} });`);
      expect(s.indexOf("      stashSocialName(")).toBeLessThan(s.indexOf("await supabase.auth.verifyOtp("));
      expect(s.match(/clearSocialNameStash\(\)/g)!.length).toBeGreaterThanOrEqual(2);
      expect(s).not.toMatch(/console\.(log|error)\([^)]*providerName/);
    }
  });
  it("Edge Function: 이번 로그인에서 조회한 이름만 providerName으로(placeholder fallback은 null), 이름/토큰 로그 없음, user_metadata 정책 유지", () => {
    for (const [file, fallback] of [["supabase/functions/naver-login/index.ts", "네이버 회원"], ["supabase/functions/kakao-login/index.ts", "카카오 회원"]] as const) {
      const s = read(file);
      expect(s).toContain("return json({ email: syntheticEmail, tokenHash, providerName });");
      const line = s.split("\n").find((l) => l.includes("const providerName"))!;
      expect(line).not.toContain(fallback);                       // fallback 이름은 providerName에 들어가지 않는다
      expect(line).toContain("|| null");
      expect(s).not.toMatch(/console\.(log|error|warn)\([^)]*(providerName|nickname|naverName|profile\.name)/);
      expect(s).not.toMatch(/accessToken[^;\n]*json\(|json\([^)]*accessToken/);   // provider access token을 응답에 싣지 않는다
    }
    expect(read("supabase/functions/naver-login/index.ts")).toContain("data: { name: naverName, naver_email: naverEmail, provider: \"naver\" }");
  });
  it("계정 병합/identity/phone/RLS 정책은 건드리지 않았다, SessionWatcher는 suggestedName prefill + 기존 검증 유지", () => {
    const a = read("lib/authAccount.ts").split("\n").filter((l) => !l.trim().startsWith("//")).join("\n");   // 주석 제외 코드만
    expect(a).not.toMatch(/account_auth_identities|linkIdentity|merged_into|signInWithOAuth/);
    const w = read("app/components/SessionWatcher.tsx");
    expect(w).toContain("account.suggestedName ?? \"\"");
    expect(w).toContain("실제 이름을 입력해주세요");
    expect(w).toContain("isAutoGeneratedName(realName, authLocalPart)");
  });
  it("SQL/DB 변경 없음(이 기능은 클라이언트 + Edge Function만)", () => {
    expect(read("lib/socialName.ts")).not.toMatch(/\.rpc\(|\.from\(/);
  });
});
